SELECT * FROM CW2.Trail;
SELECT * FROM CW2.Feature;
SELECT * FROM CW2.TrailFeature;
SELECT * FROM CW2.LocationPoint;
SELECT * FROM CW2.Users;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Trail';

